/**
 * generated by Xtext 2.18.0
 */
package org.galimatias.hello;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.galimatias.hello.HelloFactory
 * @model kind="package"
 * @generated
 */
public interface HelloPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "hello";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.galimatias.org/Hello";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "hello";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HelloPackage eINSTANCE = org.galimatias.hello.impl.HelloPackageImpl.init();

  /**
   * The meta object id for the '{@link org.galimatias.hello.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.galimatias.hello.impl.ProgramImpl
   * @see org.galimatias.hello.impl.HelloPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Webserver</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__WEBSERVER = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.galimatias.hello.impl.WifiImpl <em>Wifi</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.galimatias.hello.impl.WifiImpl
   * @see org.galimatias.hello.impl.HelloPackageImpl#getWifi()
   * @generated
   */
  int WIFI = 1;

  /**
   * The feature id for the '<em><b>Ssid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIFI__SSID = 0;

  /**
   * The feature id for the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIFI__PASSWORD = 1;

  /**
   * The number of structural features of the '<em>Wifi</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIFI_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.galimatias.hello.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.galimatias.hello.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the attribute '{@link org.galimatias.hello.Program#getWebserver <em>Webserver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Webserver</em>'.
   * @see org.galimatias.hello.Program#getWebserver()
   * @see #getProgram()
   * @generated
   */
  EAttribute getProgram_Webserver();

  /**
   * Returns the meta object for class '{@link org.galimatias.hello.Wifi <em>Wifi</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Wifi</em>'.
   * @see org.galimatias.hello.Wifi
   * @generated
   */
  EClass getWifi();

  /**
   * Returns the meta object for the attribute '{@link org.galimatias.hello.Wifi#getSsid <em>Ssid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ssid</em>'.
   * @see org.galimatias.hello.Wifi#getSsid()
   * @see #getWifi()
   * @generated
   */
  EAttribute getWifi_Ssid();

  /**
   * Returns the meta object for the attribute '{@link org.galimatias.hello.Wifi#getPassword <em>Password</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Password</em>'.
   * @see org.galimatias.hello.Wifi#getPassword()
   * @see #getWifi()
   * @generated
   */
  EAttribute getWifi_Password();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  HelloFactory getHelloFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.galimatias.hello.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.galimatias.hello.impl.ProgramImpl
     * @see org.galimatias.hello.impl.HelloPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Webserver</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM__WEBSERVER = eINSTANCE.getProgram_Webserver();

    /**
     * The meta object literal for the '{@link org.galimatias.hello.impl.WifiImpl <em>Wifi</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.galimatias.hello.impl.WifiImpl
     * @see org.galimatias.hello.impl.HelloPackageImpl#getWifi()
     * @generated
     */
    EClass WIFI = eINSTANCE.getWifi();

    /**
     * The meta object literal for the '<em><b>Ssid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WIFI__SSID = eINSTANCE.getWifi_Ssid();

    /**
     * The meta object literal for the '<em><b>Password</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WIFI__PASSWORD = eINSTANCE.getWifi_Password();

  }

} //HelloPackage
