/**
 * generated by Xtext 2.18.0
 */
package org.galimatias.hello;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.galimatias.hello.Program#getWebserver <em>Webserver</em>}</li>
 * </ul>
 *
 * @see org.galimatias.hello.HelloPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Webserver</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Webserver</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Webserver</em>' attribute.
   * @see #setWebserver(String)
   * @see org.galimatias.hello.HelloPackage#getProgram_Webserver()
   * @model
   * @generated
   */
  String getWebserver();

  /**
   * Sets the value of the '{@link org.galimatias.hello.Program#getWebserver <em>Webserver</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Webserver</em>' attribute.
   * @see #getWebserver()
   * @generated
   */
  void setWebserver(String value);

} // Program
