/**
 * generated by Xtext 2.18.0
 */
package org.galimatias.hello;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Wifi</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.galimatias.hello.Wifi#getSsid <em>Ssid</em>}</li>
 *   <li>{@link org.galimatias.hello.Wifi#getPassword <em>Password</em>}</li>
 * </ul>
 *
 * @see org.galimatias.hello.HelloPackage#getWifi()
 * @model
 * @generated
 */
public interface Wifi extends EObject
{
  /**
   * Returns the value of the '<em><b>Ssid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ssid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ssid</em>' attribute.
   * @see #setSsid(String)
   * @see org.galimatias.hello.HelloPackage#getWifi_Ssid()
   * @model
   * @generated
   */
  String getSsid();

  /**
   * Sets the value of the '{@link org.galimatias.hello.Wifi#getSsid <em>Ssid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ssid</em>' attribute.
   * @see #getSsid()
   * @generated
   */
  void setSsid(String value);

  /**
   * Returns the value of the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Password</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Password</em>' attribute.
   * @see #setPassword(String)
   * @see org.galimatias.hello.HelloPackage#getWifi_Password()
   * @model
   * @generated
   */
  String getPassword();

  /**
   * Sets the value of the '{@link org.galimatias.hello.Wifi#getPassword <em>Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Password</em>' attribute.
   * @see #getPassword()
   * @generated
   */
  void setPassword(String value);

} // Wifi
