/*
 * generated by Xtext 2.18.0
 */
package org.galimatias.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.galimatias.ide.contentassist.antlr.internal.InternalHelloParser;
import org.galimatias.services.HelloGrammarAccess;

public class HelloParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(HelloGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, HelloGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getWifiAccess().getGroup(), "rule__Wifi__Group__0");
			builder.put(grammarAccess.getProgramAccess().getWebserverAssignment(), "rule__Program__WebserverAssignment");
			builder.put(grammarAccess.getWifiAccess().getSsidAssignment_1(), "rule__Wifi__SsidAssignment_1");
			builder.put(grammarAccess.getWifiAccess().getPasswordAssignment_2(), "rule__Wifi__PasswordAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private HelloGrammarAccess grammarAccess;

	@Override
	protected InternalHelloParser createParser() {
		InternalHelloParser result = new InternalHelloParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public HelloGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HelloGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
