/**
 * generated by Xtext 2.18.0
 */
package org.galimatias.tests;

import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.galimatias.tests.HelloInjectorProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(HelloInjectorProvider.class)
@SuppressWarnings("all")
public class HelloParsingTest {
  @Test
  public void loadModel() {
  }
}
