/*
 * generated by Xtext 2.18.0
 */
package org.galimatias.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHelloScopeProvider extends DelegatingScopeProvider {
}
